# Generated by Django 4.0.6 on 2022-07-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
    ]
