# Generated by Django 4.0.6 on 2022-07-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='Images/photo_net.jpg', null=True, upload_to='Images'),
        ),
    ]
