# Generated by Django 4.0.6 on 2022-07-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='favorite',
            new_name='is_favorite',
        ),
    ]
